name: Dashboard project
on: push
jobs: 
  test: 
    runs-on: windows-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-python@v3
        with: 
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
      - name: Run test
        run: python -m unittest test.py
      
        
       
